language: node_js
node_js:
  - 10
sudo: false
services:
  - redis-server
notifications:
  email:
    - bossa@aftership.com
branches:
  only:
    - master
install:
  - . ./scripts/ci/setup.sh
script:
  - . ./scripts/ci/run.sh
