language: node_js
node_js:
  - 2.0.0
  - 4.2.3
sudo: false
services:
  - redis-server
notifications:
  email:
    - bossa@aftership.net
env:
  - CACHE_DIR=cache
cache:
  directories:
    - $CACHE_DIR
branches:
  only:
    - master
install:
  - . ./scripts/ci/setup.sh
script:
  - . ./scripts/ci/run.sh
after_script:
  - bash <(curl -s https://codecov.io/bash)
